 version: 2.1

 jobs:
   build:
     docer:
       - image : 'mcr.microsoft.com/dotnet/core/sdk:3.1'
       - image : 'circleci/node: latest'
    
     steps:
       - checkout
       - run: dotnet build
