 version: 2.1

 jobs:
   build:
     docker:
       - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
     steps:
       - checkout
       - run: find .
       - run:
          name: Restore packages
          command:
            dotnet restore
       - run: apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
       - run: curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -yq nodejs
       - run: npm install -g npm
       - run: npm install && npm update
       - run: node -v && npm -v
       - run: cd OrderManagementSupport && cd ClientApp && npm install -g @angular/cli
       - run: cd OrderManagementSupport && cd ClientApp && npm install -g @angular-devkit/schematics
       - run: cd OrderManagementSupport && cd ClientApp && npm install -g --save-dev @angular-devkit/build-angular
       - run: cd OrderManagementSupport && cd ClientApp && ls && npm install @angular/compiler --save
       - run: dotnet build
