 version: 2.1

 jobs:
   build:
     docker:
       - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
     steps:
       - checkout
       - run: apt-get sudo -y
       - run: apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
       - run: curl -sL https://deb.nodesource.com/setup_10.x | bash - && sudo apt-get install -yq nodejs
       - run: sudo npm install -g npm
       - run: sudo npm install
       - run: node -v  
       - run: npm -v  
       - run: find .
       - run:
          name: Restore packages
          command:
            dotnet restore
       - run: dotnet build
