 version: 2.1

 jobs:
   build:
     docker:
       - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
     steps:
       - checkout
       - run: apt-get update -yq && apt-get upgrade -yq && apt-get install -yq curl git nano
       - run: curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -yq nodejs
       - run: npm install -g npm
       - run: npm install
       - run: npm update
       - run: node -v  
       - run: npm -v  
       - run: npm install @angular/compiler --save 
       - run: npm install -g @angular/cli
       - run: npm install --save-dev @angular-devkit/build-angular
       - run: ng update
       - run: find .
       - run:
          name: Restore packages
          command:
            dotnet restore
       - run: dotnet build
