 version: 2.1

 jobs:
   build:
     docer:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1
       - image: circleci/node:10.16.3
    
     steps:
       - checkout
       - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
       - run: dotnet build
