 version: 2.1

 jobs:
   build:
     docker:
       - image: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
     steps:
       - checkout
       - run: RUN apt-get update
       - run: RUN apt-get install nodejs
       - run: npm install -g npm@latest
       - run: find .
       - run:
          name: Restore packages
          command:
            dotnet restore
       - run: dotnet build
